spring:
  application:
    name: core_service
  datasource:
    url: jdbc:postgresql://localhost:2221/core_service_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 1111

security:
  jwt:
    public-key: ${JWT_PUBLIC_KEY:}

integration:
  user-service:
    base-url: ${USER_SERVICE_BASE_URL:http://localhost:1115}
    oauth:
      client-id: ${SERVICE_CLIENT_ID:service-client}
      client-secret: ${SERVICE_CLIENT_SECRET:service-client-secret}
