spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:2225/user_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 1115

security:
  jwt:
    public-key: ${JWT_PUBLIC_KEY}
    private-key: ${JWT_PRIVATE_KEY}

oauth2:
  auth-server:
    issuer-uri: http://localhost:1115
    clients:
      frontend:
        client-id: ${OAUTH_FRONTEND_CLIENT_ID:frontend-app}
        client-secret: ${OAUTH_FRONTEND_CLIENT_SECRET:frontend-app-secret}
        redirect-uri: ${OAUTH_FRONTEND_REDIRECT_URI:http://localhost:3000/login/oauth2/code/frontend-app}
      service:
        client-id: ${SERVICE_CLIENT_ID:service-client}
        client-secret: ${SERVICE_CLIENT_SECRET:service-client-secret}

app:
  instability:
    enabled: ${APP_INSTABILITY_ENABLED:true}
    default-error-rate: ${APP_DEFAULT_ERROR_RATE:0.3}
    even-minute-error-rate: ${APP_EVEN_MINUTE_ERROR_RATE:0.7}


