spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:2225/user_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 1115


