services:
  kafka:
    image: bitnamilegacy/kafka:3.9
    container_name: core_service_kafka
    restart: unless-stopped
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - bank_network

  core_service:
    build:
      context: ..
      dockerfile: core_service/Dockerfile
    container_name: core-service-backend
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://core_service_db:5432/core_service_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - USER_SERVICE_BASE_URL=http://user-service-backend:1115
      - SERVICE_CLIENT_ID=${SERVICE_CLIENT_ID}
      - SERVICE_CLIENT_SECRET=${SERVICE_CLIENT_SECRET}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
    ports:
      - "1111:1111"
    depends_on:
      core_service_db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - bank_network

  core_service_db:
    image: postgres:17-alpine
    container_name: core_service_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=core_service_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "2221:5432"
    volumes:
      - postgres_data_core_service:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d core_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bank_network

volumes:
  postgres_data_core_service:
  kafka_data:



