// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserPreferences.Data;

#nullable disable

namespace UserPreferences.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260322011952_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserPreferences.Models.HiddenAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HiddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserPreferenceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserPreferenceId", "AccountId")
                        .IsUnique();

                    b.ToTable("HiddenAccounts");
                });

            modelBuilder.Entity("UserPreferences.Models.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppType")
                        .HasColumnType("integer");

                    b.Property<int>("Theme")
                        .HasMaxLength(10)
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AppType")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("UserPreferences.Models.HiddenAccount", b =>
                {
                    b.HasOne("UserPreferences.Models.UserPreference", "UserPreference")
                        .WithMany("HiddenAccounts")
                        .HasForeignKey("UserPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPreference");
                });

            modelBuilder.Entity("UserPreferences.Models.UserPreference", b =>
                {
                    b.Navigation("HiddenAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
