services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service-backend
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user_service_db:5432/user_service_db
    ports:
      - "1115:1115"
    depends_on:
      user_service_db:
        condition: service_healthy
    networks:
      - bank_network

  user_service_db:
    image: postgres:17-alpine
    container_name: user_service_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=user_service_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "2225:5432"
    volumes:
      - postgres_data_user_service:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bank_network

volumes:
  postgres_data_user_service:



